"""add user bot photo cache

Revision ID: 299602286322
Revises: ee6d0896d1c8
Create Date: 2026-09-16 20:45:40.458987
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '299602286322'
down_revision: Union[str, None] = 'ee6d0896d1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_photos', sa.Column('user_bot_file_id', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_photos', 'user_bot_file_id')
    # ### end Alembic commands ###
